spring:
  application:
    name: ecommerce

  # Cấu hình Kết nối PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5433/nhan_ecom_db
    username: root
    password: root
    driver-class-name: org.postgresql.Driver

  # Cấu hình Hibernate JPA
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create # Tự động tạo và cập nhật bảng từ Java Entity (Rất tiện khi học/dev)
    show-sql: true     # In các câu lệnh SQL ra Console để bạn dễ theo dõi và debug
    properties:
      hibernate:
        globally_quoted_identifiers: true
        format_sql: true # Định dạng câu SQL rõ ràng, dễ đọc
        default_schema: public

# Cấu hình Web Server
server:
  port: 8080
  servlet:
    context-path: /api/v1 # Tiền tố chuẩn cho các RESTful API của bạn
jwt:
  signKey : 5245eb7eff69e9b2903c7398afcb9ee74579bbb6bb65ba11431d206da5af0367